create table if not exists public.lark_user_map (
  lark_open_id text primary key,
  staff_name text not null,
  display_name text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lark_message_log (
  id bigint generated by default as identity primary key,
  lark_open_id text,
  message_text text,
  created_at timestamptz not null default now()
);

alter table public.lark_user_map enable row level security;
alter table public.lark_message_log enable row level security;

drop policy if exists "service role manages lark user map" on public.lark_user_map;
drop policy if exists "service role manages lark message log" on public.lark_message_log;

create policy "service role manages lark user map"
on public.lark_user_map
for all
to service_role
using (true)
with check (true);

create policy "service role manages lark message log"
on public.lark_message_log
for all
to service_role
using (true)
with check (true);
