create table if not exists public.availability_submissions (
  id bigint generated by default as identity primary key,
  staff_name text not null,
  lark_open_id text,
  week_start date not null,
  availability_text text not null,
  created_at timestamptz not null default now()
);

alter table public.availability_submissions enable row level security;

grant insert on public.availability_submissions to anon;
grant select, insert, update, delete on public.availability_submissions to service_role;
grant usage, select on sequence public.availability_submissions_id_seq to anon;
grant usage, select on sequence public.availability_submissions_id_seq to service_role;

drop policy if exists "public can submit availability" on public.availability_submissions;
drop policy if exists "service role manages availability submissions" on public.availability_submissions;

create policy "public can submit availability"
on public.availability_submissions
for insert
to anon
with check (
  length(trim(staff_name)) between 1 and 120
  and length(trim(availability_text)) between 1 and 4000
);

create policy "service role manages availability submissions"
on public.availability_submissions
for all
to service_role
using (true)
with check (true);
